#spring.application.name=Task_6
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=Rohan@webkorps

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

